services:
  analyser:
    build: .
    command: ["-m", "mistralan.services.analyser"]
  tei:
    image: "ghcr.io/huggingface/text-embeddings-inference:89-1.5"
    command: --model-id mixedbread-ai/mxbai-embed-large-v1
    ports:
      - "8081:80"
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]  # specify GPU capabilities